services:
  projectflow.api:
    image: ${DOCKER_REGISTRY-}projectflowapi
    container_name: ProjectFlow.Api
    build:
      context: .
      dockerfile: ProjectFlow.Api/Dockerfile
    depends_on:
      - projectflow-db

  projectflow-db:
    image: postgres:17
    container_name: ProjectFlow.Db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ProjectFlow
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: